apiVersion: v1
kind: Service
metadata:
  name: {{ include "finance-tracker.fullname" . }}-api
  labels:
    {{- include "finance-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.apiPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "finance-tracker.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
